### ISSUE TITLE
QTextBrowser'a hatalı basım

### ISSUE THREAD

**Issue by yuceturkomer** [CSE343-2016-G2/GTUVOS#13]
Otuputun yazıldığı QTextBrowser'da, komut girilip output alındıktan sonra tıklanma olursa, tıklanılan yerden itibaren yeni outputu basıyor.

![screenshot from 2016-11-28 10 57 55](https://cloud.githubusercontent.com/assets/17343509/20660255/41b5252c-b551-11e6-896e-1361eb364581.png)

**Comment by hmenn** [comment]
Ömer tarafindan son giderildi.

**Comment by hmenn** [comment]
Ömer tarafindan son giderildi.
